### ISSUE TITLE
你好，我在模仿你的monaco editor过程中发现了一些问题。

### ISSUE THREAD

**Issue by zearoby** [kailunfan/PyQt5Playground#1]
1. 请问你的PyQt5Playground中monaco编辑器界面右击（调出菜单），程序会发生退出。
2. 如果Monaco编辑器中存在一个网址链接（如：https://github.com），然后将鼠标移到这个链接上程序也会发生退出。

请问你的有出现这两种情况吗？ 谢谢，刚开始用GitHub，还不太熟悉，请见谅。
给了小星星⭐哦，😀

![image](https://user-images.githubusercontent.com/22544491/65009330-d407ee00-d93e-11e9-9803-5ddf66025c96.png)

**Comment by kailunfan** [comment]
实在不好意思~

试了下我这里没出现描述的情况.

我的依赖版本如下:
```bash
PyQt5==5.10.1
PyQtWebEngine==5.13.0
```

大概率你已经把问题解决了,还是把我的想法说下,并表达我的歉意.

- 可以试下使用浏览器直接打开webview加载的html,看下是否有错误;
- 如果想让python解释器抛出错误时不退出程序,可以在程序入口添加如下代码:

    ```python
    import cgitb

    cgitb.enable(format="text")
    ```

**Comment by zearoby** [comment]
您好，首先非常感谢你的回答，我确实已经解决了，**我的解决办法**如下：使用PyQt5.12.1或5.12.2版本就会出现这样的问题，更换5.11.3或5.13以上版本的PyQt则不会出现这样的问题。**我的做法**是使用5.11.3的PyQt，然后用5.13.2的QWebWidget模块替换5.11.3里面的QWeb相关文件，这样既可以直接使用PDF功能，也不会出现这样的问题。
        **还有一个问题**想要请教一下您，我在citrix环境中(公司的远程桌面简称Virtual Desktop)使用5.12.3及以上版本时，打开QWebEngine会出现Opengl的错误，请问你有这样的经历吗？不知道是不是新版本的QWebEngine启用了什么新功能或新插件导致的，谢谢您。

**Comment by kailunfan** [comment]
不好意思,没遇见过这种情况.
